server {
    listen 80;
    server_name _;

    # FILE MANAGER
    location / {
        proxy_pass http://localhost:5000;
    }

    # API
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://localhost:8001;
    }

    location = /api {
        return 301 /api/;
    }

    # STATIC APPS
    location /JadwalShalat/ {
        root /apps/repo;
        index index.html;
    }

    location /DroneQC/ {
        root /apps/repo;
        index index.html;
    }

    location /cuaca/ {
        root /apps/repo;
        index index.html;
    }

    location /KoordinatConverter/ {
        root /apps/repo;
        index index.html;
    }

    location /M4e_KMLtoKMZ/ {
        root /apps/repo;
        index index.html;
    }
}
